// src/lib/currencies.ts
//
// Supported entry-fee currencies. Single source of truth shared by:
//   - the Sanity schema's currency dropdown
//     (src/sanity/schemaTypes/raceGuideType.ts)
//   - the enrichment pipeline's currency validation
//     (src/lib/raceEnrichment.ts)
// Plain module (no sanity imports) so server code can use it without
// dragging the Studio toolchain in.

// Majors first (the currencies most of the dataset uses), then the
// comprehensive world set alphabetically by code — covering every
// country with a race an editor plausibly adds (Prague CZK,
// Budapest HUF, Petra JOD, Kilimanjaro TZS, Angkor KHR, …).
export const CURRENCY_OPTIONS = [
  { title: "USD - US Dollar", value: "USD" },
  { title: "EUR - Euro", value: "EUR" },
  { title: "GBP - British Pound", value: "GBP" },
  { title: "JPY - Japanese Yen", value: "JPY" },
  { title: "AUD - Australian Dollar", value: "AUD" },
  { title: "CAD - Canadian Dollar", value: "CAD" },
  { title: "CHF - Swiss Franc", value: "CHF" },
  { title: "CNY - Chinese Yuan", value: "CNY" },
  { title: "SEK - Swedish Krona", value: "SEK" },
  { title: "DKK - Danish Krone", value: "DKK" },
  { title: "NZD - New Zealand Dollar", value: "NZD" },
  { title: "MXN - Mexican Peso", value: "MXN" },
  { title: "SGD - Singapore Dollar", value: "SGD" },
  { title: "HKD - Hong Kong Dollar", value: "HKD" },
  { title: "NOK - Norwegian Krone", value: "NOK" },
  { title: "KRW - South Korean Won", value: "KRW" },
  { title: "TRY - Turkish Lira", value: "TRY" },
  { title: "INR - Indian Rupee", value: "INR" },
  { title: "BRL - Brazilian Real", value: "BRL" },
  { title: "ZAR - South African Rand", value: "ZAR" },
  { title: "THB - Thai Baht", value: "THB" },
  { title: "QAR - Qatari Riyal", value: "QAR" },
  // ── World set (alphabetical by code) ──────────────────────────
  { title: "AED - UAE Dirham", value: "AED" },
  { title: "ALL - Albanian Lek", value: "ALL" },
  { title: "AMD - Armenian Dram", value: "AMD" },
  { title: "ARS - Argentine Peso", value: "ARS" },
  { title: "AZN - Azerbaijani Manat", value: "AZN" },
  { title: "BAM - Bosnian Convertible Mark", value: "BAM" },
  { title: "BDT - Bangladeshi Taka", value: "BDT" },
  { title: "BGN - Bulgarian Lev", value: "BGN" },
  { title: "BHD - Bahraini Dinar", value: "BHD" },
  { title: "BOB - Bolivian Boliviano", value: "BOB" },
  { title: "BWP - Botswana Pula", value: "BWP" },
  { title: "BYN - Belarusian Ruble", value: "BYN" },
  { title: "CLP - Chilean Peso", value: "CLP" },
  { title: "COP - Colombian Peso", value: "COP" },
  { title: "CRC - Costa Rican Colón", value: "CRC" },
  { title: "CZK - Czech Koruna", value: "CZK" },
  { title: "DOP - Dominican Peso", value: "DOP" },
  { title: "DZD - Algerian Dinar", value: "DZD" },
  { title: "EGP - Egyptian Pound", value: "EGP" },
  { title: "ETB - Ethiopian Birr", value: "ETB" },
  { title: "FJD - Fijian Dollar", value: "FJD" },
  { title: "GEL - Georgian Lari", value: "GEL" },
  { title: "GTQ - Guatemalan Quetzal", value: "GTQ" },
  { title: "HNL - Honduran Lempira", value: "HNL" },
  { title: "HUF - Hungarian Forint", value: "HUF" },
  { title: "IDR - Indonesian Rupiah", value: "IDR" },
  { title: "ILS - Israeli New Shekel", value: "ILS" },
  { title: "ISK - Icelandic Króna", value: "ISK" },
  { title: "JMD - Jamaican Dollar", value: "JMD" },
  { title: "JOD - Jordanian Dinar", value: "JOD" },
  { title: "KES - Kenyan Shilling", value: "KES" },
  { title: "KHR - Cambodian Riel", value: "KHR" },
  { title: "KWD - Kuwaiti Dinar", value: "KWD" },
  { title: "KZT - Kazakhstani Tenge", value: "KZT" },
  { title: "LKR - Sri Lankan Rupee", value: "LKR" },
  { title: "MAD - Moroccan Dirham", value: "MAD" },
  { title: "MDL - Moldovan Leu", value: "MDL" },
  { title: "MKD - Macedonian Denar", value: "MKD" },
  { title: "MNT - Mongolian Tögrög", value: "MNT" },
  { title: "MUR - Mauritian Rupee", value: "MUR" },
  { title: "MYR - Malaysian Ringgit", value: "MYR" },
  { title: "NAD - Namibian Dollar", value: "NAD" },
  { title: "NGN - Nigerian Naira", value: "NGN" },
  { title: "NPR - Nepalese Rupee", value: "NPR" },
  { title: "OMR - Omani Rial", value: "OMR" },
  { title: "PAB - Panamanian Balboa", value: "PAB" },
  { title: "PEN - Peruvian Sol", value: "PEN" },
  { title: "PHP - Philippine Peso", value: "PHP" },
  { title: "PKR - Pakistani Rupee", value: "PKR" },
  { title: "PLN - Polish Złoty", value: "PLN" },
  { title: "PYG - Paraguayan Guaraní", value: "PYG" },
  { title: "RON - Romanian Leu", value: "RON" },
  { title: "RSD - Serbian Dinar", value: "RSD" },
  { title: "RUB - Russian Ruble", value: "RUB" },
  { title: "RWF - Rwandan Franc", value: "RWF" },
  { title: "SAR - Saudi Riyal", value: "SAR" },
  { title: "TND - Tunisian Dinar", value: "TND" },
  { title: "TWD - New Taiwan Dollar", value: "TWD" },
  { title: "TZS - Tanzanian Shilling", value: "TZS" },
  { title: "UAH - Ukrainian Hryvnia", value: "UAH" },
  { title: "UGX - Ugandan Shilling", value: "UGX" },
  { title: "UYU - Uruguayan Peso", value: "UYU" },
  { title: "VND - Vietnamese Dong", value: "VND" },
  { title: "XAF - Central African CFA Franc", value: "XAF" },
  { title: "XOF - West African CFA Franc", value: "XOF" },
  { title: "ZMW - Zambian Kwacha", value: "ZMW" },
] as const;

export const CURRENCY_CODES: ReadonlySet<string> = new Set(
  CURRENCY_OPTIONS.map((o) => o.value),
);
