// src/lib/iocCountries.ts
//
// IOC / World Athletics 3-letter country codes used for course-record
// athletes. Single source of truth shared by:
//   - the Sanity schema's four record-country dropdowns
//     (src/sanity/schemaTypes/raceGuideType.ts)
//   - the enrichment pipeline's country validation
//     (src/lib/raceEnrichment.ts)
// Plain module (no sanity imports) so server code can use it without
// dragging the Studio toolchain in.

export const IOC_COUNTRY_OPTIONS = [
  { title: "Afghanistan", value: "AFG" },
  { title: "Albania", value: "ALB" },
  { title: "Algeria", value: "ALG" },
  { title: "Andorra", value: "AND" },
  { title: "Angola", value: "ANG" },
  { title: "Argentina", value: "ARG" },
  { title: "Armenia", value: "ARM" },
  { title: "Australia", value: "AUS" },
  { title: "Austria", value: "AUT" },
  { title: "Azerbaijan", value: "AZE" },
  { title: "Bahamas", value: "BAH" },
  { title: "Bahrain", value: "BRN" },
  { title: "Bangladesh", value: "BAN" },
  { title: "Barbados", value: "BAR" },
  { title: "Belarus", value: "BLR" },
  { title: "Belgium", value: "BEL" },
  { title: "Belize", value: "BIZ" },
  { title: "Benin", value: "BEN" },
  { title: "Bermuda", value: "BER" },
  { title: "Bhutan", value: "BHU" },
  { title: "Bolivia", value: "BOL" },
  { title: "Bosnia and Herzegovina", value: "BIH" },
  { title: "Botswana", value: "BOT" },
  { title: "Brazil", value: "BRA" },
  { title: "Bulgaria", value: "BUL" },
  { title: "Burkina Faso", value: "BUR" },
  { title: "Burundi", value: "BDI" },
  { title: "Cambodia", value: "CAM" },
  { title: "Cameroon", value: "CMR" },
  { title: "Canada", value: "CAN" },
  { title: "Chile", value: "CHI" },
  { title: "China", value: "CHN" },
  { title: "Colombia", value: "COL" },
  { title: "Costa Rica", value: "CRC" },
  { title: "Croatia", value: "CRO" },
  { title: "Cuba", value: "CUB" },
  { title: "Cyprus", value: "CYP" },
  { title: "Czech Republic", value: "CZE" },
  { title: "Denmark", value: "DEN" },
  { title: "Djibouti", value: "DJI" },
  { title: "Dominican Republic", value: "DOM" },
  { title: "Ecuador", value: "ECU" },
  { title: "Egypt", value: "EGY" },
  { title: "El Salvador", value: "ESA" },
  { title: "Eritrea", value: "ERI" },
  { title: "Estonia", value: "EST" },
  { title: "Ethiopia", value: "ETH" },
  { title: "Finland", value: "FIN" },
  { title: "France", value: "FRA" },
  { title: "Georgia", value: "GEO" },
  { title: "Germany", value: "GER" },
  { title: "Ghana", value: "GHA" },
  { title: "Great Britain", value: "GBR" },
  { title: "Greece", value: "GRE" },
  { title: "Guatemala", value: "GUA" },
  { title: "Guinea", value: "GUI" },
  { title: "Haiti", value: "HAI" },
  { title: "Honduras", value: "HON" },
  { title: "Hong Kong", value: "HKG" },
  { title: "Hungary", value: "HUN" },
  { title: "Iceland", value: "ISL" },
  { title: "India", value: "IND" },
  { title: "Indonesia", value: "INA" },
  { title: "Iran", value: "IRI" },
  { title: "Iraq", value: "IRQ" },
  { title: "Ireland", value: "IRL" },
  { title: "Israel", value: "ISR" },
  { title: "Italy", value: "ITA" },
  { title: "Jamaica", value: "JAM" },
  { title: "Japan", value: "JPN" },
  { title: "Jordan", value: "JOR" },
  { title: "Kazakhstan", value: "KAZ" },
  { title: "Kenya", value: "KEN" },
  { title: "Kuwait", value: "KUW" },
  { title: "Kyrgyzstan", value: "KGZ" },
  { title: "Latvia", value: "LAT" },
  { title: "Lebanon", value: "LIB" },
  { title: "Lesotho", value: "LES" },
  { title: "Lithuania", value: "LTU" },
  { title: "Luxembourg", value: "LUX" },
  { title: "Malaysia", value: "MAS" },
  { title: "Malta", value: "MLT" },
  { title: "Mauritius", value: "MRI" },
  { title: "Mexico", value: "MEX" },
  { title: "Moldova", value: "MDA" },
  { title: "Monaco", value: "MON" },
  { title: "Mongolia", value: "MGL" },
  { title: "Montenegro", value: "MNE" },
  { title: "Morocco", value: "MAR" },
  { title: "Mozambique", value: "MOZ" },
  { title: "Namibia", value: "NAM" },
  { title: "Nepal", value: "NEP" },
  { title: "Netherlands", value: "NED" },
  { title: "New Zealand", value: "NZL" },
  { title: "Nicaragua", value: "NCA" },
  { title: "Nigeria", value: "NGR" },
  { title: "North Korea", value: "PRK" },
  { title: "North Macedonia", value: "MKD" },
  { title: "Norway", value: "NOR" },
  { title: "Oman", value: "OMA" },
  { title: "Pakistan", value: "PAK" },
  { title: "Palestine", value: "PLE" },
  { title: "Panama", value: "PAN" },
  { title: "Paraguay", value: "PAR" },
  { title: "Peru", value: "PER" },
  { title: "Philippines", value: "PHI" },
  { title: "Poland", value: "POL" },
  { title: "Portugal", value: "POR" },
  { title: "Puerto Rico", value: "PUR" },
  { title: "Qatar", value: "QAT" },
  { title: "Romania", value: "ROU" },
  { title: "Russia", value: "RUS" },
  { title: "Rwanda", value: "RWA" },
  { title: "Saudi Arabia", value: "KSA" },
  { title: "Serbia", value: "SRB" },
  { title: "Singapore", value: "SGP" },
  { title: "Slovakia", value: "SVK" },
  { title: "Slovenia", value: "SLO" },
  { title: "Somalia", value: "SOM" },
  { title: "South Africa", value: "RSA" },
  { title: "South Korea", value: "KOR" },
  { title: "South Sudan", value: "SSD" },
  { title: "Spain", value: "ESP" },
  { title: "Sri Lanka", value: "SRI" },
  { title: "Sudan", value: "SUD" },
  { title: "Sweden", value: "SWE" },
  { title: "Switzerland", value: "SUI" },
  { title: "Syria", value: "SYR" },
  { title: "Taiwan", value: "TPE" },
  { title: "Tajikistan", value: "TJK" },
  { title: "Tanzania", value: "TAN" },
  { title: "Thailand", value: "THA" },
  { title: "Trinidad and Tobago", value: "TTO" },
  { title: "Tunisia", value: "TUN" },
  { title: "Turkey", value: "TUR" },
  { title: "Turkmenistan", value: "TKM" },
  { title: "Uganda", value: "UGA" },
  { title: "Ukraine", value: "UKR" },
  { title: "United Arab Emirates", value: "UAE" },
  { title: "United States", value: "USA" },
  { title: "Uruguay", value: "URU" },
  { title: "Uzbekistan", value: "UZB" },
  { title: "Venezuela", value: "VEN" },
  { title: "Vietnam", value: "VIE" },
  { title: "Yemen", value: "YEM" },
  { title: "Zambia", value: "ZAM" },
  { title: "Zimbabwe", value: "ZIM" },
] as const;

export const IOC_COUNTRY_CODES: ReadonlySet<string> = new Set(
  IOC_COUNTRY_OPTIONS.map((o) => o.value),
);
