// src/sanity/schemaTypes/raceGuideType.ts

import { defineType, defineField } from 'sanity'
import { PinIcon } from '@sanity/icons'

export const raceGuideType = defineType({
  name: 'raceGuide',
  title: 'Race Guide',
  type: 'document',
  icon: PinIcon,
  fieldsets: [
    {
      name: 'dateRefresh',
      title: 'Date Refresh (auto-scraped)',
      options: { collapsible: true, collapsed: true },
    },
  ],
  fields: [
    defineField({
      name: 'title',
      type: 'string',
    }),
    defineField({
      name: 'slug',
      type: 'slug',
      options: {
        source: 'title',
      },
    }),
    defineField({
      name: 'city',
      title: 'City',
      type: 'string',
    }),
    defineField({
      name: 'stateRegion',
      title: 'State/Region',
      type: 'string',
    }),
    defineField({
      name: 'country',
      title: 'Country',
      type: 'string',
    }),
    defineField({
      name: 'eventDate',
      type: 'datetime',
    }),
    defineField({
      name: 'mainImage',
      title: 'Main Image (landscape)',
      type: 'image',
      options: { hotspot: true },
      description:
        'Used on the homepage row, /races index card, and OG share image. Landscape (~3:2 / 16:9) framing recommended.',
    }),
    defineField({
      name: 'portraitImage',
      title: 'Portrait Image (3:4)',
      type: 'image',
      options: { hotspot: true },
      description:
        'Tall hero image rendered in the side panel of the race detail page. 3:4 portrait framing recommended; falls back to Main Image if not set.',
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published At',
      type: 'datetime',
      description: 'When this race guide was published (used for sorting breaking news)',
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      to: [{ type: 'author' }],
      description:
        'Editorial byline for the race guide write-up. Optional — leave empty for races without long-form content.',
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      description: 'A short summary of the race guide for previews (120–160 characters recommended)',
      validation: (Rule) => Rule.max(200),
    }),
    defineField({
      name: 'raceCategory',
      title: 'Race Category',
      type: 'reference',
      to: [{ type: 'raceCategory' }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'distance',
      title: 'Distance (km)',
      type: 'number',
      description: 'Exact race distance in kilometers (e.g., 42.195 for marathon, 21.0975 for half marathon)',
    }),
    defineField({
      name: 'surface',
      title: 'Surface',
      type: 'string',
      options: {
        list: [
          { title: 'Road', value: 'Road' },
          { title: 'Trail', value: 'Trail' },
          { title: 'Track', value: 'Track' },
          { title: 'Mountain', value: 'Mountain' },
          { title: 'Mixed', value: 'Mixed' },
        ],
      },
    }),
    defineField({
      name: 'surfaceBreakdown',
      title: 'Surface Breakdown',
      type: 'string',
      description: 'Detailed surface composition of the course',
      options: {
        list: [
          { title: '100% Paved', value: '100% Paved' },
          { title: 'Unpaved', value: 'Unpaved' },
          { title: 'Mixed', value: 'Mixed' },
        ],
      },
    }),
    defineField({
      name: 'profile',
      title: 'Profile',
      type: 'string',
      description: 'Course elevation profile - consider both distance and net elevation when classifying',
      options: {
        list: [
          { title: 'Flat', value: 'flat' },
          { title: 'Rolling', value: 'rolling' },
          { title: 'Hilly', value: 'hilly' },
          { title: 'Mountainous', value: 'mountainous' },
        ],
      },
    }),
    defineField({
      name: 'elevationGain',
      title: 'Elevation Gain (meters)',
      type: 'number',
    }),
    defineField({
      name: 'elevationLoss',
      title: 'Elevation Loss (meters)',
      type: 'number',
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Add multiple tags to categorize this race (e.g., "World Athletics Gold", "Major Marathon", "Fast Course")',
    }),
    defineField({
      name: 'finishers',
      title: 'Number of Finishers 2025',
      type: 'number',
    }),
    defineField({
      name: 'fieldSize',
      title: 'Field Size',
      type: 'number',
      description:
        'Total field size (capacity / number of runners). Drives the "Field size" stat tile on the race detail page; falls back to `finishers` until this is populated per race.',
    }),
    defineField({
      name: 'price',
      title: 'Entry Price',
      type: 'number',
      description: 'Entry price in the local currency',
    }),
    defineField({
      name: 'currency',
      title: 'Currency',
      type: 'string',
      description: 'Currency of the entry price',
      options: {
        list: [
          { title: 'USD - US Dollar', value: 'USD' },
          { title: 'EUR - Euro', value: 'EUR' },
          { title: 'GBP - British Pound', value: 'GBP' },
          { title: 'JPY - Japanese Yen', value: 'JPY' },
          { title: 'AUD - Australian Dollar', value: 'AUD' },
          { title: 'CAD - Canadian Dollar', value: 'CAD' },
          { title: 'CHF - Swiss Franc', value: 'CHF' },
          { title: 'CNY - Chinese Yuan', value: 'CNY' },
          { title: 'SEK - Swedish Krona', value: 'SEK' },
          { title: 'DKK - Danish Krone', value: 'DKK' },
          { title: 'NZD - New Zealand Dollar', value: 'NZD' },
          { title: 'MXN - Mexican Peso', value: 'MXN' },
          { title: 'SGD - Singapore Dollar', value: 'SGD' },
          { title: 'HKD - Hong Kong Dollar', value: 'HKD' },
          { title: 'NOK - Norwegian Krone', value: 'NOK' },
          { title: 'KRW - South Korean Won', value: 'KRW' },
          { title: 'TRY - Turkish Lira', value: 'TRY' },
          { title: 'INR - Indian Rupee', value: 'INR' },
          { title: 'BRL - Brazilian Real', value: 'BRL' },
          { title: 'ZAR - South African Rand', value: 'ZAR' },
          { title: 'THB - Thai Baht', value: 'THB' },
          { title: 'QAR - Qatari Riyal', value: 'QAR' },
        ],
      },
      initialValue: 'USD',
    }),
    defineField({
      name: 'altitude',
      title: 'Altitude (metres above sea level)',
      type: 'number',
      description:
        'Course altitude in metres above sea level. Drives the "Altitude" stat tile on the race detail page; used to derive a label (Sea level / Highland / Mountain) automatically.',
    }),
    defineField({
      name: 'humidity',
      title: 'Average Humidity (%)',
      type: 'number',
      description:
        'Average relative humidity at race time, 0–100. Drives the "Humidity" stat tile; auto-labelled Dry / Moderate / Humid.',
      validation: (Rule) => Rule.min(0).max(100),
    }),
    defineField({
      name: 'averageTemperature',
      title: 'Average Temperature (°C)',
      type: 'number',
    }),
    defineField({
      name: 'mensCourseRecord',
      title: "Men's Course Record",
      type: 'string',
      description: 'Format: HH:MM:SS',
    }),
    defineField({
      name: 'mensCourseRecordAthlete',
      title: "Men's Course Record Athlete",
      type: 'string',
      description: 'Name of the athlete who holds the men\'s course record',
    }),
    defineField({
      name: 'mensCourseRecordCountry',
      title: "Men's Course Record Country",
      type: 'string',
      description: 'Country of the athlete',
      options: {
        list: [
          { title: 'Afghanistan', value: 'AFG' },
          { title: 'Albania', value: 'ALB' },
          { title: 'Algeria', value: 'ALG' },
          { title: 'Andorra', value: 'AND' },
          { title: 'Angola', value: 'ANG' },
          { title: 'Argentina', value: 'ARG' },
          { title: 'Armenia', value: 'ARM' },
          { title: 'Australia', value: 'AUS' },
          { title: 'Austria', value: 'AUT' },
          { title: 'Azerbaijan', value: 'AZE' },
          { title: 'Bahamas', value: 'BAH' },
          { title: 'Bahrain', value: 'BRN' },
          { title: 'Bangladesh', value: 'BAN' },
          { title: 'Barbados', value: 'BAR' },
          { title: 'Belarus', value: 'BLR' },
          { title: 'Belgium', value: 'BEL' },
          { title: 'Belize', value: 'BIZ' },
          { title: 'Benin', value: 'BEN' },
          { title: 'Bermuda', value: 'BER' },
          { title: 'Bhutan', value: 'BHU' },
          { title: 'Bolivia', value: 'BOL' },
          { title: 'Bosnia and Herzegovina', value: 'BIH' },
          { title: 'Botswana', value: 'BOT' },
          { title: 'Brazil', value: 'BRA' },
          { title: 'Bulgaria', value: 'BUL' },
          { title: 'Burkina Faso', value: 'BUR' },
          { title: 'Burundi', value: 'BDI' },
          { title: 'Cambodia', value: 'CAM' },
          { title: 'Cameroon', value: 'CMR' },
          { title: 'Canada', value: 'CAN' },
          { title: 'Chile', value: 'CHI' },
          { title: 'China', value: 'CHN' },
          { title: 'Colombia', value: 'COL' },
          { title: 'Costa Rica', value: 'CRC' },
          { title: 'Croatia', value: 'CRO' },
          { title: 'Cuba', value: 'CUB' },
          { title: 'Cyprus', value: 'CYP' },
          { title: 'Czech Republic', value: 'CZE' },
          { title: 'Denmark', value: 'DEN' },
          { title: 'Djibouti', value: 'DJI' },
          { title: 'Dominican Republic', value: 'DOM' },
          { title: 'Ecuador', value: 'ECU' },
          { title: 'Egypt', value: 'EGY' },
          { title: 'El Salvador', value: 'ESA' },
          { title: 'Eritrea', value: 'ERI' },
          { title: 'Estonia', value: 'EST' },
          { title: 'Ethiopia', value: 'ETH' },
          { title: 'Finland', value: 'FIN' },
          { title: 'France', value: 'FRA' },
          { title: 'Georgia', value: 'GEO' },
          { title: 'Germany', value: 'GER' },
          { title: 'Ghana', value: 'GHA' },
          { title: 'Great Britain', value: 'GBR' },
          { title: 'Greece', value: 'GRE' },
          { title: 'Guatemala', value: 'GUA' },
          { title: 'Guinea', value: 'GUI' },
          { title: 'Haiti', value: 'HAI' },
          { title: 'Honduras', value: 'HON' },
          { title: 'Hong Kong', value: 'HKG' },
          { title: 'Hungary', value: 'HUN' },
          { title: 'Iceland', value: 'ISL' },
          { title: 'India', value: 'IND' },
          { title: 'Indonesia', value: 'INA' },
          { title: 'Iran', value: 'IRI' },
          { title: 'Iraq', value: 'IRQ' },
          { title: 'Ireland', value: 'IRL' },
          { title: 'Israel', value: 'ISR' },
          { title: 'Italy', value: 'ITA' },
          { title: 'Jamaica', value: 'JAM' },
          { title: 'Japan', value: 'JPN' },
          { title: 'Jordan', value: 'JOR' },
          { title: 'Kazakhstan', value: 'KAZ' },
          { title: 'Kenya', value: 'KEN' },
          { title: 'Kuwait', value: 'KUW' },
          { title: 'Kyrgyzstan', value: 'KGZ' },
          { title: 'Latvia', value: 'LAT' },
          { title: 'Lebanon', value: 'LIB' },
          { title: 'Lesotho', value: 'LES' },
          { title: 'Lithuania', value: 'LTU' },
          { title: 'Luxembourg', value: 'LUX' },
          { title: 'Malaysia', value: 'MAS' },
          { title: 'Malta', value: 'MLT' },
          { title: 'Mauritius', value: 'MRI' },
          { title: 'Mexico', value: 'MEX' },
          { title: 'Moldova', value: 'MDA' },
          { title: 'Monaco', value: 'MON' },
          { title: 'Mongolia', value: 'MGL' },
          { title: 'Montenegro', value: 'MNE' },
          { title: 'Morocco', value: 'MAR' },
          { title: 'Mozambique', value: 'MOZ' },
          { title: 'Namibia', value: 'NAM' },
          { title: 'Nepal', value: 'NEP' },
          { title: 'Netherlands', value: 'NED' },
          { title: 'New Zealand', value: 'NZL' },
          { title: 'Nicaragua', value: 'NCA' },
          { title: 'Nigeria', value: 'NGR' },
          { title: 'North Korea', value: 'PRK' },
          { title: 'North Macedonia', value: 'MKD' },
          { title: 'Norway', value: 'NOR' },
          { title: 'Oman', value: 'OMA' },
          { title: 'Pakistan', value: 'PAK' },
          { title: 'Palestine', value: 'PLE' },
          { title: 'Panama', value: 'PAN' },
          { title: 'Paraguay', value: 'PAR' },
          { title: 'Peru', value: 'PER' },
          { title: 'Philippines', value: 'PHI' },
          { title: 'Poland', value: 'POL' },
          { title: 'Portugal', value: 'POR' },
          { title: 'Puerto Rico', value: 'PUR' },
          { title: 'Qatar', value: 'QAT' },
          { title: 'Romania', value: 'ROU' },
          { title: 'Russia', value: 'RUS' },
          { title: 'Rwanda', value: 'RWA' },
          { title: 'Saudi Arabia', value: 'KSA' },
          { title: 'Serbia', value: 'SRB' },
          { title: 'Singapore', value: 'SGP' },
          { title: 'Slovakia', value: 'SVK' },
          { title: 'Slovenia', value: 'SLO' },
          { title: 'Somalia', value: 'SOM' },
          { title: 'South Africa', value: 'RSA' },
          { title: 'South Korea', value: 'KOR' },
          { title: 'South Sudan', value: 'SSD' },
          { title: 'Spain', value: 'ESP' },
          { title: 'Sri Lanka', value: 'SRI' },
          { title: 'Sudan', value: 'SUD' },
          { title: 'Sweden', value: 'SWE' },
          { title: 'Switzerland', value: 'SUI' },
          { title: 'Syria', value: 'SYR' },
          { title: 'Taiwan', value: 'TPE' },
          { title: 'Tajikistan', value: 'TJK' },
          { title: 'Tanzania', value: 'TAN' },
          { title: 'Thailand', value: 'THA' },
          { title: 'Trinidad and Tobago', value: 'TTO' },
          { title: 'Tunisia', value: 'TUN' },
          { title: 'Turkey', value: 'TUR' },
          { title: 'Turkmenistan', value: 'TKM' },
          { title: 'Uganda', value: 'UGA' },
          { title: 'Ukraine', value: 'UKR' },
          { title: 'United Arab Emirates', value: 'UAE' },
          { title: 'United States', value: 'USA' },
          { title: 'Uruguay', value: 'URU' },
          { title: 'Uzbekistan', value: 'UZB' },
          { title: 'Venezuela', value: 'VEN' },
          { title: 'Vietnam', value: 'VIE' },
          { title: 'Yemen', value: 'YEM' },
          { title: 'Zambia', value: 'ZAM' },
          { title: 'Zimbabwe', value: 'ZIM' },
        ],
        layout: 'dropdown',
      },
    }),
    defineField({
      name: 'womensCourseRecord',
      title: "Women's Course Record",
      type: 'string',
      description: 'Format: HH:MM:SS',
    }),
    defineField({
      name: 'womensCourseRecordAthlete',
      title: "Women's Course Record Athlete",
      type: 'string',
      description: 'Name of the athlete who holds the women\'s course record',
    }),
    defineField({
      name: 'womensCourseRecordCountry',
      title: "Women's Course Record Country",
      type: 'string',
      description: 'Country of the athlete',
      options: {
        list: [
          { title: 'Afghanistan', value: 'AFG' },
          { title: 'Albania', value: 'ALB' },
          { title: 'Algeria', value: 'ALG' },
          { title: 'Andorra', value: 'AND' },
          { title: 'Angola', value: 'ANG' },
          { title: 'Argentina', value: 'ARG' },
          { title: 'Armenia', value: 'ARM' },
          { title: 'Australia', value: 'AUS' },
          { title: 'Austria', value: 'AUT' },
          { title: 'Azerbaijan', value: 'AZE' },
          { title: 'Bahamas', value: 'BAH' },
          { title: 'Bahrain', value: 'BRN' },
          { title: 'Bangladesh', value: 'BAN' },
          { title: 'Barbados', value: 'BAR' },
          { title: 'Belarus', value: 'BLR' },
          { title: 'Belgium', value: 'BEL' },
          { title: 'Belize', value: 'BIZ' },
          { title: 'Benin', value: 'BEN' },
          { title: 'Bermuda', value: 'BER' },
          { title: 'Bhutan', value: 'BHU' },
          { title: 'Bolivia', value: 'BOL' },
          { title: 'Bosnia and Herzegovina', value: 'BIH' },
          { title: 'Botswana', value: 'BOT' },
          { title: 'Brazil', value: 'BRA' },
          { title: 'Bulgaria', value: 'BUL' },
          { title: 'Burkina Faso', value: 'BUR' },
          { title: 'Burundi', value: 'BDI' },
          { title: 'Cambodia', value: 'CAM' },
          { title: 'Cameroon', value: 'CMR' },
          { title: 'Canada', value: 'CAN' },
          { title: 'Chile', value: 'CHI' },
          { title: 'China', value: 'CHN' },
          { title: 'Colombia', value: 'COL' },
          { title: 'Costa Rica', value: 'CRC' },
          { title: 'Croatia', value: 'CRO' },
          { title: 'Cuba', value: 'CUB' },
          { title: 'Cyprus', value: 'CYP' },
          { title: 'Czech Republic', value: 'CZE' },
          { title: 'Denmark', value: 'DEN' },
          { title: 'Djibouti', value: 'DJI' },
          { title: 'Dominican Republic', value: 'DOM' },
          { title: 'Ecuador', value: 'ECU' },
          { title: 'Egypt', value: 'EGY' },
          { title: 'El Salvador', value: 'ESA' },
          { title: 'Eritrea', value: 'ERI' },
          { title: 'Estonia', value: 'EST' },
          { title: 'Ethiopia', value: 'ETH' },
          { title: 'Finland', value: 'FIN' },
          { title: 'France', value: 'FRA' },
          { title: 'Georgia', value: 'GEO' },
          { title: 'Germany', value: 'GER' },
          { title: 'Ghana', value: 'GHA' },
          { title: 'Great Britain', value: 'GBR' },
          { title: 'Greece', value: 'GRE' },
          { title: 'Guatemala', value: 'GUA' },
          { title: 'Guinea', value: 'GUI' },
          { title: 'Haiti', value: 'HAI' },
          { title: 'Honduras', value: 'HON' },
          { title: 'Hong Kong', value: 'HKG' },
          { title: 'Hungary', value: 'HUN' },
          { title: 'Iceland', value: 'ISL' },
          { title: 'India', value: 'IND' },
          { title: 'Indonesia', value: 'INA' },
          { title: 'Iran', value: 'IRI' },
          { title: 'Iraq', value: 'IRQ' },
          { title: 'Ireland', value: 'IRL' },
          { title: 'Israel', value: 'ISR' },
          { title: 'Italy', value: 'ITA' },
          { title: 'Jamaica', value: 'JAM' },
          { title: 'Japan', value: 'JPN' },
          { title: 'Jordan', value: 'JOR' },
          { title: 'Kazakhstan', value: 'KAZ' },
          { title: 'Kenya', value: 'KEN' },
          { title: 'Kuwait', value: 'KUW' },
          { title: 'Kyrgyzstan', value: 'KGZ' },
          { title: 'Latvia', value: 'LAT' },
          { title: 'Lebanon', value: 'LIB' },
          { title: 'Lesotho', value: 'LES' },
          { title: 'Lithuania', value: 'LTU' },
          { title: 'Luxembourg', value: 'LUX' },
          { title: 'Malaysia', value: 'MAS' },
          { title: 'Malta', value: 'MLT' },
          { title: 'Mauritius', value: 'MRI' },
          { title: 'Mexico', value: 'MEX' },
          { title: 'Moldova', value: 'MDA' },
          { title: 'Monaco', value: 'MON' },
          { title: 'Mongolia', value: 'MGL' },
          { title: 'Montenegro', value: 'MNE' },
          { title: 'Morocco', value: 'MAR' },
          { title: 'Mozambique', value: 'MOZ' },
          { title: 'Namibia', value: 'NAM' },
          { title: 'Nepal', value: 'NEP' },
          { title: 'Netherlands', value: 'NED' },
          { title: 'New Zealand', value: 'NZL' },
          { title: 'Nicaragua', value: 'NCA' },
          { title: 'Nigeria', value: 'NGR' },
          { title: 'North Korea', value: 'PRK' },
          { title: 'North Macedonia', value: 'MKD' },
          { title: 'Norway', value: 'NOR' },
          { title: 'Oman', value: 'OMA' },
          { title: 'Pakistan', value: 'PAK' },
          { title: 'Palestine', value: 'PLE' },
          { title: 'Panama', value: 'PAN' },
          { title: 'Paraguay', value: 'PAR' },
          { title: 'Peru', value: 'PER' },
          { title: 'Philippines', value: 'PHI' },
          { title: 'Poland', value: 'POL' },
          { title: 'Portugal', value: 'POR' },
          { title: 'Puerto Rico', value: 'PUR' },
          { title: 'Qatar', value: 'QAT' },
          { title: 'Romania', value: 'ROU' },
          { title: 'Russia', value: 'RUS' },
          { title: 'Rwanda', value: 'RWA' },
          { title: 'Saudi Arabia', value: 'KSA' },
          { title: 'Serbia', value: 'SRB' },
          { title: 'Singapore', value: 'SGP' },
          { title: 'Slovakia', value: 'SVK' },
          { title: 'Slovenia', value: 'SLO' },
          { title: 'Somalia', value: 'SOM' },
          { title: 'South Africa', value: 'RSA' },
          { title: 'South Korea', value: 'KOR' },
          { title: 'South Sudan', value: 'SSD' },
          { title: 'Spain', value: 'ESP' },
          { title: 'Sri Lanka', value: 'SRI' },
          { title: 'Sudan', value: 'SUD' },
          { title: 'Sweden', value: 'SWE' },
          { title: 'Switzerland', value: 'SUI' },
          { title: 'Syria', value: 'SYR' },
          { title: 'Taiwan', value: 'TPE' },
          { title: 'Tajikistan', value: 'TJK' },
          { title: 'Tanzania', value: 'TAN' },
          { title: 'Thailand', value: 'THA' },
          { title: 'Trinidad and Tobago', value: 'TTO' },
          { title: 'Tunisia', value: 'TUN' },
          { title: 'Turkey', value: 'TUR' },
          { title: 'Turkmenistan', value: 'TKM' },
          { title: 'Uganda', value: 'UGA' },
          { title: 'Ukraine', value: 'UKR' },
          { title: 'United Arab Emirates', value: 'UAE' },
          { title: 'United States', value: 'USA' },
          { title: 'Uruguay', value: 'URU' },
          { title: 'Uzbekistan', value: 'UZB' },
          { title: 'Venezuela', value: 'VEN' },
          { title: 'Vietnam', value: 'VIE' },
          { title: 'Yemen', value: 'YEM' },
          { title: 'Zambia', value: 'ZAM' },
          { title: 'Zimbabwe', value: 'ZIM' },
        ],
        layout: 'dropdown',
      },
    }),
    defineField({
      name: 'officialWebsite',
      title: 'Official Race Website',
      type: 'url',
      description: 'URL to the official race website',
    }),
    defineField({
      name: 'gpxFile',
      title: 'Route File (GeoJSON or GPX)',
      type: 'file',
      description: 'Upload the GeoJSON (.geojson, .json) or GPX (.gpx) file containing the race route coordinates. GeoJSON is preferred for better performance.',
      options: {
        accept: '.geojson,.json,.gpx',
      },
    }),
    defineField({
      name: 'featuredRace',
      title: 'Featured Race Guide',
      type: 'boolean',
      initialValue: false,
      validation: (Rule) =>
        Rule.custom(async (value, context) => {
          if (!value) return true

          const id = context.document?._id
          if (!id) return true

          const existing = await context.getClient({ apiVersion: '2021-10-21' }).fetch(
            `*[_type == "raceGuide" && featuredRace == true && _id != $id][0]._id`,
            { id }
          )

          return !existing || 'Only one featured race guide is allowed.'
        }),
    }),
    defineField({
      name: 'isBreaking',
      title: 'Show in Breaking News Section',
      type: 'boolean',
      initialValue: false,
      description: 'Show this race guide in the homepage breaking news section',
    }),
    defineField({
      name: 'introduction',
      title: 'Introduction',
      type: 'blockContent',
      description:
        'Leading paragraph(s) shown above the main body on the race detail page.',
    }),
    defineField({
      name: 'body',
      type: 'blockContent',
    }),
    defineField({
      name: 'suggestedNextDate',
      title: 'Suggested Next Date',
      type: 'datetime',
      fieldset: 'dateRefresh',
      description:
        'Auto-scraped suggestion from the official website. Approve to copy into eventDate; reject to discard.',
      readOnly: true,
    }),
    defineField({
      name: 'suggestedNextDateScrapedAt',
      title: 'Scraped At',
      type: 'datetime',
      fieldset: 'dateRefresh',
      readOnly: true,
    }),
    defineField({
      name: 'suggestedNextDateSourceQuote',
      title: 'Source Quote',
      type: 'text',
      fieldset: 'dateRefresh',
      description: 'Verbatim phrase the date was extracted from.',
      readOnly: true,
    }),
    defineField({
      name: 'suggestedNextDateStatus',
      title: 'Status',
      type: 'string',
      fieldset: 'dateRefresh',
      options: {
        list: [
          { title: 'Pending review', value: 'pending' },
          { title: 'Approved', value: 'approved' },
          { title: 'Rejected', value: 'rejected' },
        ],
      },
      description:
        'Editor sets this. "Approved" → manually copy suggestedNextDate into eventDate, then clear status to re-enable scraping.',
    }),
    defineField({
      name: 'lastScanAt',
      title: 'Last Scanned At',
      type: 'datetime',
      fieldset: 'dateRefresh',
      description:
        'Set on EVERY scan attempt (success or failure), so the row can show the scan history even when no suggestion was written.',
      readOnly: true,
    }),
    defineField({
      name: 'lastScanLog',
      title: 'Last Scan Log (JSON)',
      type: 'text',
      fieldset: 'dateRefresh',
      description:
        'JSON-encoded breakdown of the most recent scan: pages fetched, sources used, Haiku reasoning, confidence. Surfaced in the admin Date Review row expander.',
      readOnly: true,
    }),
  ],
})